name: vocaday_app
description: "An English Vocabulary learing app."
publish_to: "none"

version: 1.0.8+9

environment:
  sdk: ^3.8.1

dependencies:
  audioplayers: ^6.5.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.9
  collection: ^1.19.1
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_storage: ^12.4.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_card_swiper: ^7.0.2
  flutter_heatmap_calendar: ^1.0.5
  flutter_local_notifications: ^19.3.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  fpdart: ^1.1.1
  get_it: ^8.0.3
  go_router: ^15.2.4
  google_fonts: ^6.2.1
  google_sign_in: ^7.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  like_button: ^2.1.0
  logger: ^2.6.0
  lottie: ^3.3.1
  path: ^1.9.1
  percent_indicator: ^4.2.5
  permission_handler: ^12.0.0+1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  timezone: ^0.10.1
  tutorial_coach_mark: ^1.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.5.4
  flutter_gen: ^5.10.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo_1024.png"
  adaptive_icon_background: "#ff3b47de"

flutter_gen:
  output: lib/app/constants/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: false
    flare_flutter: false
    rive: false
    lottie: false

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/jsons/
    - assets/translations/
    - assets/data/
    - assets/sounds/

  fonts:
    # - family: Roboto_300 # Light - w300
    #   fonts:
    #     - asset: assets/fonts/Roboto-Light.ttf
    #     - asset: assets/fonts/Roboto-LightItalic.ttf
    #       style: italic
    - family: Roboto # Regular - w400
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-RegularItalic.ttf
          style: italic
    # - family: Roboto_500 # Medium - w500
    #   fonts:
    #     - asset: assets/fonts/Roboto-Medium.ttf
    #     - asset: assets/fonts/Roboto-MediumItalic.ttf
    #       style: italic
    # - family: Roboto_700 # Bold - w700
    #   fonts:
    #     - asset: assets/fonts/Roboto-Bold.ttf
    #     - asset: assets/fonts/Roboto-BoldItalic.ttf
    #       style: italic
